#!/usr/bin/env bash

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]; then
    scp $1 ubuntu@$2:~
elif [ $# -gt 3 ]; then
    scp $1 ubuntu@$2:$3
fi
