#!/usr/bin/env bash
# Script that install nginx

if [ -x "$(command -v nginx)" ]; then
  echo "is installed.";
else
    apt update && apt install nginx -y;
fi

service nginx start;
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default;
service nginx restart;
echo "Holberton School" > /var/www/html/index.nginx-debian.html;

nginx -s reload;
