#!/usr/bin/env bash
# Script that install nginxchange 404

if ! [ -x "$(command -v nginx)" ]; then
    apt update -y;
    apt install nginx -y;
fi

service nginx start;
echo "Holberton School" > /var/www/html/index.nginx-debian.html;
service nginx restart;

filea="/etc/nginx/sites-available/default"
filee="/etc/nginx/sites-enabled/default"

#redirect
sed -i "/listen 80 default_server;/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4? permanent;" $filea;

#404
touch /var/www/html/404.html;
echo "Ceci n'est pas une page" > /var/www/html/404.html;
sed -i "/listen 80 default_server;/a \\\terror_page 404 /404.html;" $filea;

#ADD HEADER
sed -i "/listen 80 default_server;/a \\\tadd_header X-Served-By $HOSTNAME;" $filea;
service nginx restart;
