#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

if ! [ -x "$(command -v haproxy)" ]; then
    apt update -y;
    apt install -y haproxy;
fi
haproxy -v;
service haproxy start;

configfile="/etc/haproxy/haproxy.cfg"

#redirect
if [ -f $configfile ]; then
grep "frontend firstbalance" -q "$configfile" || sed -i -e '$afrontend firstbalance \n\tbind *:80 \n\t#option forwardfor \n\tdefault_backend webservers' $configfile;
grep "backend webservers" -q "$configfile" || sed -i -e '$abackend webservers \n\tbalance roundrobin \n\tserver webserver1 104.196.43.40:80 check \n\tserver webserver2 54.91.178.63:80 check' $configfile;
fi
service haproxy restart;
