#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=0
while [ $i -le 10 ]
do
    if [ $i = 9 ]
    then
    echo "Hi"
    else
    echo "Holberton School"
    fi
    (( i++ ))
done
