#!/usr/bin/env bash
#  content of the current directory

FILE=holbertonschool
if test -e "$FILE";then
    echo "holbertonschool file exists"
    if test -s "$FILE";then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if test -f "$FILE"
        echo "is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
