#!/usr/bin/env bash
#Script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
