#!/usr/bin/env bash
# put nginx to listen in port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
service nginx stop
chmod a+rwx /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
